sudo: required
language: ruby
services:
        - docker

before_script:
        # - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin   #login to dockerhub
        # - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - heroku login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

script:
        - docker-compose build
        - docker tag rails-thelighthouse/$TAG registry.heroku.com/$HEROKU_APP/web 
          
deploy:   
        provider: script
        script: 
               docker push registry.heroku.com/$HEROKU_APP/web
            #    docker push aabhusan/koora:v1;
            #    docker push registry.heroku.com/$HEROKU_APP/web;
               heroku container:release web --app $HEROKU_APP
        # on:
        #   branch: $TRAVIS_BRANCH