sudo: required

services:
  - docker

language: ruby

before_script:
    # - heroku login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

script:
    - docker-compose build
    - docker tag rails-thelighthouse/$TAG registry.heroku.com/$HEROKU_APP/web 
          
deploy:   
    provider: heroku
    api_key: $HEROKU_API_KEY
    script: 
        docker push registry.heroku.com/$HEROKU_APP/web
        heroku container:release web --app $HEROKU_APP