version: '3.8'

volumes: 
  postgres_data:
  bundle:
  node_modules:
  packs:
  rails_cache:

services:
  app:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: ruby

    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - $HOME/.ssh/:/home/ruby/.ssh/ # Mount the ssh folder to authenticate with github
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
      - .psqlrc:/root/.psqlrc:ro
    environment:
      HUB_URL: http://chrome:4444/wd/hub
      PARALLEL_WORKERS: 1 # makes tests run sequentially instead of parallelizing them
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on: 
      - database
      - chrome

  database:
    image: postgres
    restart: unless-stopped
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm