meta_product_name: "The Lighthouse"
meta_title: "The Lighthouse - Carreira e Propósito"
meta_description: "Uma consultoria inspiradora, focada em orientação de carreira e propósito para aqueles que buscam uma vida mais feliz e alinhada ao que faz sentido pra si."
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards