meta_product_name: "The Lighthouse"
meta_title: "The Lighthouse - Carreira e Propósito"
meta_description: "A The Lighthouse é para todos aqueles que buscam ter uma vida profissional mais feliz e alinhada ao que faz sentido para si."
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards