name: Test

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
         
    - name: Docker meta
      uses: docker/metadata-action@v3
      with:
        images: |
          isabtra/rails-thelighthouse_test
    # - name: Build docker images
    #   run: docker-compose -f.ci/docker-compose.test.yml build
      
    - name: Build and cache docker image
      uses: docker/bake-action@master
      with:
        files: |
          .ci/docker-compose.test.yml
          ${{ steps.docker_meta.outputs.bake-file }}

    - name: Run tests
      run: docker-compose -f .ci/docker-compose.test.yml run test