name: Test

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
      CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      MAILGUN_ADDRESS: ${{ secrets.MAILGUN_ADDRESS }}
      MAILGUN_PORT: ${{ secrets.MAILGUN_PORT }}
      MAILGUN_USER: ${{ secrets.MAILGUN_USER }}
      MAIL_DOMAIN: ${{ secrets.MAIL_DOMAIN }}
    runs-on: ubuntu-latest # runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build docker images
      run: docker-compose -f.ci/docker-compose.test.yml build
      
    # - name: Start Container
    #   run: docker-compose up

    - name: Run tests
      run: docker-compose -f .ci/docker-compose.test.yml run test